package com.github.loki.afro.metallum.enums;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Represents the encyclopedia metallum mapping of countries.
 *
 * Since the iso country lists are updated every few years, this enum shall too.
 *
 * The problem lies in the detail here, for some occasions there is no iso code only the "display name" of a country which can lead to mapping failures
 *
 * example of such an mapping failure:
 * java: Czech Republic, metallum: Czechia (which is actually correct since 1993)
 *
 * also one can not guarantee how and when the archivists are about to add a locale or rename a country.
 *
 * @author Zarathustra
 */
public enum Country {

    ANY("ANY"),
    AF("Afghanistan"),
    AX("Åland Islands"),
    AL("Albania"),
    DZ("Algeria"),
    AS("American Samoa"),
    AD("Andorra"),
    AO("Angola"),
    AI("Anguilla"),
    AQ("Antarctica"),
    AG("Antigua and Barbuda"),
    AR("Argentina"),
    AM("Armenia"),
    AW("Aruba"),
    AU("Australia"),
    AT("Austria"),
    AZ("Azerbaijan"),
    BS("Bahamas"),
    BH("Bahrain"),
    BD("Bangladesh"),
    BB("Barbados"),
    BY("Belarus"),
    BE("Belgium"),
    BZ("Belize"),
    BJ("Benin"),
    BM("Bermuda"),
    BT("Bhutan"),
    BO("Bolivia"),
    BQ("Bonaire, Sint Eustatius and Saba"),
    BA("Bosnia and Herzegovina"),
    BW("Botswana"),
    BV("Bouvet Island"),
    BR("Brazil"),
    IO("British Indian Ocean Territory"),
    BN("Brunei"),
    BG("Bulgaria"),
    BF("Burkina Faso"),
    BI("Burundi"),
    KH("Cambodia"),
    CM("Cameroon"),
    CA("Canada"),
    CV("Cape Verde"),
    KY("Cayman Islands"),
    CF("Central African Republic"),
    TD("Chad"),
    CL("Chile"),
    CN("China"),
    CX("Christmas Island"),
    CC("Cocos (Keeling) Islands"),
    CO("Colombia"),
    KM("Comoros"),
    CD("Congo, Democratic Republic of"),
    CG("Congo, Republic of"),
    CK("Cook Islands"),
    CR("Costa Rica"),
    HR("Croatia"),
    CU("Cuba"),
    CW("Curaçao"),
    CY("Cyprus"),
    CZ("Czechia"),
    DK("Denmark"),
    DJ("Djibouti"),
    DM("Dominica"),
    DO("Dominican Republic"),
    TL("East Timor"),
    EC("Ecuador"),
    EG("Egypt"),
    SV("El Salvador"),
    GQ("Equatorial Guinea"),
    ER("Eritrea"),
    EE("Estonia"),
    SZ("Eswatini"),
    ET("Ethiopia"),
    FK("Falkland Islands"),
    FO("Faroe Islands"),
    FJ("Fiji"),
    FI("Finland"),
    FR("France"),
    GF("French Guiana"),
    PF("French Polynesia"),
    TF("French Southern Territories"),
    GA("Gabon"),
    GM("Gambia"),
    GE("Georgia"),
    DE("Germany"),
    GH("Ghana"),
    GI("Gibraltar"),
    GR("Greece"),
    GL("Greenland"),
    GD("Grenada"),
    GP("Guadeloupe"),
    GU("Guam"),
    GT("Guatemala"),
    GG("Guernsey"),
    GN("Guinea"),
    GW("Guinea-Bissau"),
    GY("Guyana"),
    HT("Haiti"),
    HM("Heard and McDonald Islands"),
    HN("Honduras"),
    HK("Hong Kong"),
    HU("Hungary"),
    IS("Iceland"),
    IN("India"),
    ID("Indonesia"),
    XX("International"),
    IR("Iran"),
    IQ("Iraq"),
    IE("Ireland"),
    IM("Isle of Man"),
    IL("Israel"),
    IT("Italy"),
    CI("Ivory Coast"),
    JM("Jamaica"),
    JP("Japan"),
    JE("Jersey"),
    JO("Jordan"),
    KZ("Kazakhstan"),
    KE("Kenya"),
    KI("Kiribati"),
    KP("Korea, North"),
    KR("Korea, South"),
    KW("Kuwait"),
    KG("Kyrgyzstan"),
    LA("Laos"),
    LV("Latvia"),
    LB("Lebanon"),
    LS("Lesotho"),
    LR("Liberia"),
    LY("Libya"),
    LI("Liechtenstein"),
    LT("Lithuania"),
    LU("Luxembourg"),
    MO("Macau"),
    MG("Madagascar"),
    MW("Malawi"),
    MY("Malaysia"),
    MV("Maldives"),
    ML("Mali"),
    MT("Malta"),
    MH("Marshall Islands"),
    MQ("Martinique"),
    MR("Mauritania"),
    MU("Mauritius"),
    YT("Mayotte"),
    MX("Mexico"),
    FM("Micronesia, Federated States of"),
    MD("Moldova"),
    MC("Monaco"),
    MN("Mongolia"),
    ME("Montenegro"),
    MS("Montserrat"),
    MA("Morocco"),
    MZ("Mozambique"),
    MM("Myanmar"),
    NA("Namibia"),
    NR("Nauru"),
    NP("Nepal"),
    NL("Netherlands"),
    NC("New Caledonia"),
    NZ("New Zealand"),
    NI("Nicaragua"),
    NE("Niger"),
    NG("Nigeria"),
    NU("Niue"),
    NF("Norfolk Island"),
    MK("North Macedonia"),
    MP("Northern Mariana Islands"),
    NO("Norway"),
    OM("Oman"),
    PK("Pakistan"),
    PW("Palau"),
    PS("Palestine"),
    PA("Panama"),
    PG("Papua New Guinea"),
    PY("Paraguay"),
    PE("Peru"),
    PH("Philippines"),
    PN("Pitcairn Island"),
    PL("Poland"),
    PT("Portugal"),
    PR("Puerto Rico"),
    QA("Qatar"),
    RE("Reunion"),
    RO("Romania"),
    RU("Russia"),
    RW("Rwanda"),
    BL("Saint Barthélemy"),
    KN("Saint Kitts & Nevis"),
    LC("Saint Lucia"),
    MF("Saint Martin (French part)"),
    PM("Saint Pierre and Miquelon"),
    VC("Saint Vincent and The Grenadines"),
    WS("Samoa"),
    SM("San Marino"),
    ST("Sao Tome and Principe"),
    SA("Saudi Arabia"),
    SN("Senegal"),
    RS("Serbia"),
    SC("Seychelles"),
    SL("Sierra Leone"),
    SG("Singapore"),
    SX("Sint Maarten (Dutch part)"),
    SK("Slovakia"),
    SI("Slovenia"),
    SB("Solomon Islands"),
    SO("Somalia"),
    ZA("South Africa"),
    GS("South Georgia & South Sandwich Islands"),
    SS("South Sudan"),
    ES("Spain"),
    LK("Sri Lanka"),
    SH("St Helena, Ascension & Tristan da Cunha"),
    SD("Sudan"),
    SR("Suriname"),
    SJ("Svalbard"),
    SE("Sweden"),
    CH("Switzerland"),
    SY("Syria"),
    TW("Taiwan"),
    TJ("Tajikistan"),
    TZ("Tanzania"),
    TH("Thailand"),
    TG("Togo"),
    TK("Tokelau"),
    TO("Tonga"),
    TT("Trinidad and Tobago"),
    TN("Tunisia"),
    TR("Turkey"),
    TM("Turkmenistan"),
    TC("Turks and Caicos Islands"),
    TV("Tuvalu"),
    UM("U.S. Minor Outlying Islands"),
    UG("Uganda"),
    UA("Ukraine"),
    AE("United Arab Emirates"),
    GB("United Kingdom"),
    US("United States"),
    ZZ("Unknown"),
    UY("Uruguay"),
    UZ("Uzbekistan"),
    VU("Vanuatu"),
    VA("Vatican City"),
    VE("Venezuela"),
    VN("Vietnam"),
    VG("Virgin Islands (British)"),
    VI("Virgin Islands (US)"),
    WF("Wallis and Futuna"),
    EH("Western Sahara"),
    YE("Yemen"),
    ZM("Zambia"),
    ZW("Zimbabwe");
    private final String fullName;

    private static final Logger logger = LoggerFactory.getLogger(Country.class);

    Country(final String fullName) {
        this.fullName = fullName;
    }

    public String getFullName() {
        return this.fullName;
    }

    public String getShortForm() {
        return this.name();
    }

    public static Country ofMetallumDisplayName(String possiblecountry) {
        possiblecountry = possiblecountry.trim();
        for (final Country country : values()) {
            if (country.fullName.equalsIgnoreCase(possiblecountry)) {
                return country;
            }
        }
        logger.warn("Unrecognized Country: " + possiblecountry);
        return Country.ANY;
    }

}
